<a href="https://colab.research.google.com/github/taratrou/matsue-ct-ruby-lectue/blob/master/test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

a = np.array([0,1,2,3])

a = a.reshape(2,2)

print(a)

[[0 1]
 [2 3]]


In [ ]:
b = np.array([2,3,4,5])

b = b.reshape(2,2)

print(a + b)

[[2 4]
 [6 8]]


In [ ]:
print(a@b)

[[ 4  5]
 [16 21]]
